### ISSUE TITLE
Command Dispatch Error

### ISSUE THREAD

**Issue by Sandarr95** [Azim-D3Tm/TGConsole#1]
Hi,

I'm running your plugin on spigotmc 1.14.4.
I receive messages properly, getid works when I put it to true.

However when I run a command nothing happens and in the logs it shows:
```
[18:58:07] [Server thread/INFO]: Done (46.761s)! For help, type "help"
[18:58:15] [GompcraftBot Telegram Executor/INFO]: got update;
[18:58:15] [GompcraftBot Telegram Executor/INFO]: it have text;
[18:58:15] [GompcraftBot Telegram Executor/INFO]: is admin
[18:58:15] [GompcraftBot Telegram Executor/INFO]: User: Sander Kolman @SanderK
[18:58:15] [GompcraftBot Telegram Executor/INFO]: Action: say Something
[18:58:15] [GompcraftBot Telegram Executor/ERROR]: BOTSESSION
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:708) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-2012f1e]
	at ru.stormcraft.tgconsole.util.ConsoleUtils.executeCommand(ConsoleUtils.java:20) ~[TGConsole-1.12.jar:?]
	at ru.stormcraft.tgconsole.TGself.onUpdateReceived(TGself.java:141) ~[TGConsole-1.12.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBotsAPI.jar:?]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306) [TelegramBotsAPI.jar:?]
```

If you need more information I'd be happy to provide it.

**Comment by Sandarr95** [comment]
Btw, I am a programmer, never did a lot with Java but with some pointers I'm sure I could get a working PR

**Comment by Azim-D3Tm** [comment]
I abandoned the plugin a while ago due to me not having the proxy for bot and general lack of interest.
You are free to make a fork and change whatever you want

**Comment by Azim-D3Tm** [comment]
Sorry, but i dont think i will come back to it any time soon

**Comment by Sandarr95** [comment]
Thanks for the reply, ill try to figure it out

**Comment by Azim-D3Tm** [comment]
Keep in mind that the code here may differ from the last release on spigot.

**Comment by Azim-D3Tm** [comment]
@Sandarr95 you can check spigot page for latest version (i changed from githib to bitbuckit, so no commits here about that)

I will delete this repisitory this month.
